version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: saas_financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - saas_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/saas_financeiro
      SECRET_KEY: your-secret-key-change-in-production
      STRIPE_SECRET_KEY: sk_test_your_stripe_key
      PAGBRASIL_API_KEY: your_pagbrasil_key
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - saas_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_your_stripe_key
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - saas_network
    command: npm start

volumes:
  postgres_data:

networks:
  saas_network:
    driver: bridge