# Configuração de Deploy Automático no Render
# Este arquivo define todos os serviços necessários para o SaaS Financeiro

services:
  # Banco de Dados PostgreSQL
  - type: pserv
    name: saas-financeiro-db
    env: docker
    plan: free
    dockerfilePath: ./database/Dockerfile
    envVars:
      - key: POSTGRES_DB
        value: saas_financeiro
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: saas-financeiro-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Backend FastAPI
  - type: web
    name: saas-financeiro-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: saas-financeiro-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true

  # Frontend React
  - type: web
    name: saas-financeiro-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: saas-financeiro-backend
          property: host
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

# Configurações globais
databases:
  - name: saas-financeiro-db
    databaseName: saas_financeiro
    user: postgres
    plan: free

# Configuração de notificações
notifications:
  - type: email
    emails:
      - seu-email@exemplo.com
    events:
      - deploy-succeeded
      - deploy-failed
      - service-suspended